/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalapp;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohiuddin Khan Rafi (x22128271)
 */
public class PatientsGUI extends javax.swing.JFrame {
    private ArrayList<Patients> patients;
    /**
     * Creates new form PatientsGUI
     */
    public PatientsGUI() {
        initComponents();
        symptomsLbl.setVisible(false);
        symptomsTf.setVisible(false);
        symDurationLbl.setVisible(false);
        symDurationTf.setVisible(false);
        injurTypeLbl.setVisible(false);
        injurTypeTf.setVisible(false);
        bloodPLbl.setVisible(false);
        bloodPTf.setVisible(false);
        operationLbl.setVisible(false);
        operationTf.setVisible(false);
        concentLbl.setVisible(false);
        concentTf.setVisible(false);
        patients = new ArrayList<>();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1Lbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        guardNamLbl = new javax.swing.JLabel();
        ppsnLbl = new javax.swing.JLabel();
        symptomsLbl = new javax.swing.JLabel();
        symDurationLbl = new javax.swing.JLabel();
        injurTypeLbl = new javax.swing.JLabel();
        bloodPLbl = new javax.swing.JLabel();
        operationLbl = new javax.swing.JLabel();
        concentLbl = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        ageTf = new javax.swing.JTextField();
        guardNamTf = new javax.swing.JTextField();
        ppsnTf = new javax.swing.JTextField();
        symptomsTf = new javax.swing.JTextField();
        symDurationTf = new javax.swing.JTextField();
        injurTypeTf = new javax.swing.JTextField();
        bloodPTf = new javax.swing.JTextField();
        operationTf = new javax.swing.JTextField();
        concentTf = new javax.swing.JTextField();
        ordinaryPatientsRb = new javax.swing.JRadioButton();
        injuredPatientsRb = new javax.swing.JRadioButton();
        criticalPatientsRb = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        menuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        title1Lbl.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        title1Lbl.setText("Patient Registration Form");

        nameLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nameLbl.setText("Name:");

        ageLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ageLbl.setText("Age:");

        guardNamLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        guardNamLbl.setText("Guardian Name:");

        ppsnLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ppsnLbl.setText("PPSN:");

        symptomsLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        symptomsLbl.setText("Symptoms:");

        symDurationLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        symDurationLbl.setText("Symptom Duration:");

        injurTypeLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        injurTypeLbl.setText("Injury Type:");

        bloodPLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bloodPLbl.setText("Blood Pressure:");

        operationLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        operationLbl.setText("Operation:");

        concentLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        concentLbl.setText("Concent:");

        nameTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });

        ageTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        guardNamTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        ppsnTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        symptomsTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        symDurationTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        injurTypeTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        bloodPTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        operationTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        concentTf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        ordinaryPatientsRb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ordinaryPatientsRb.setText("Ordinary Patient");
        ordinaryPatientsRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordinaryPatientsRbActionPerformed(evt);
            }
        });

        injuredPatientsRb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        injuredPatientsRb.setText("Injured Patient");
        injuredPatientsRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                injuredPatientsRbActionPerformed(evt);
            }
        });

        criticalPatientsRb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        criticalPatientsRb.setText("Critical Patient");
        criticalPatientsRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criticalPatientsRbActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        removeBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        menuBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuBtn.setText("Menu");
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(ageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(guardNamLbl)
                            .addComponent(symptomsLbl)
                            .addComponent(ppsnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(symDurationLbl)
                            .addComponent(injurTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(operationLbl)
                            .addComponent(concentLbl)
                            .addComponent(bloodPLbl))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(menuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(55, 55, 55)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title1Lbl)
                    .addComponent(nameTf)
                    .addComponent(guardNamTf)
                    .addComponent(ageTf)
                    .addComponent(ppsnTf)
                    .addComponent(symptomsTf)
                    .addComponent(symDurationTf)
                    .addComponent(injurTypeTf)
                    .addComponent(bloodPTf)
                    .addComponent(operationTf)
                    .addComponent(concentTf)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(criticalPatientsRb)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(clearBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ordinaryPatientsRb)
                    .addComponent(injuredPatientsRb))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ordinaryPatientsRb))
                    .addComponent(ageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guardNamTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(injuredPatientsRb))
                    .addComponent(guardNamLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ppsnTf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(criticalPatientsRb))
                    .addComponent(ppsnLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(symptomsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(symptomsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(symDurationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(symDurationLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(injurTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(injurTypeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodPTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodPLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(operationTf, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(operationLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(concentLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(concentTf)
                                .addComponent(clearBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(displayBtn)
                            .addComponent(searchBtn)
                            .addComponent(removeBtn))))
                .addGap(27, 27, 27)
                .addComponent(menuBtn)
                .addGap(163, 163, 163))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordinaryPatientsRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordinaryPatientsRbActionPerformed
        // TODO add your handling code here:
        symptomsLbl.setVisible(true);
        symptomsTf.setVisible(true);
        symDurationLbl.setVisible(true);
        symDurationTf.setVisible(true);
        injurTypeLbl.setVisible(false);
        injurTypeTf.setVisible(false);
        bloodPLbl.setVisible(false);
        bloodPTf.setVisible(false);
        operationLbl.setVisible(false);
        operationTf.setVisible(false);
        concentLbl.setVisible(false);
        concentTf.setVisible(false);
        
    }//GEN-LAST:event_ordinaryPatientsRbActionPerformed

    private void injuredPatientsRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_injuredPatientsRbActionPerformed
        // TODO add your handling code here:
        symptomsLbl.setVisible(false);
        symptomsTf.setVisible(false);
        symDurationLbl.setVisible(false);
        symDurationTf.setVisible(false);
        injurTypeLbl.setVisible(true);
        injurTypeTf.setVisible(true);
        bloodPLbl.setVisible(true);
        bloodPTf.setVisible(true);
        operationLbl.setVisible(false);
        operationTf.setVisible(false);
        concentLbl.setVisible(false);
        concentTf.setVisible(false);
    }//GEN-LAST:event_injuredPatientsRbActionPerformed

    private void criticalPatientsRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criticalPatientsRbActionPerformed
        // TODO add your handling code here:
        symptomsLbl.setVisible(false);
        symptomsTf.setVisible(false);
        symDurationLbl.setVisible(false);
        symDurationTf.setVisible(false);
        injurTypeLbl.setVisible(false);
        injurTypeTf.setVisible(false);
        bloodPLbl.setVisible(false);
        bloodPTf.setVisible(false);
        operationLbl.setVisible(true);
        operationTf.setVisible(true);
        concentLbl.setVisible(true);
        concentTf.setVisible(true);
    }//GEN-LAST:event_criticalPatientsRbActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if (ordinaryPatientsRb.isSelected()) {
            //declare and create a new manager object m
            OrdinaryPatients o = new OrdinaryPatients();

            o.setName(nameTf.getText());
            o.setAge(ageTf.getText());
            o.setGuardNam(guardNamTf.getText());
            o.setPpsn(ppsnTf.getText());
            o.setSymptoms(symptomsTf.getText());
            o.setSymDuration(symDurationTf.getText());
            patients.add(o);
        
        }else if (injuredPatientsRb.isSelected()) {

            InjuredPatients i = new InjuredPatients();
            i.setName(nameTf.getText());
            i.setAge(ageTf.getText());
            i.setGuardNam(guardNamTf.getText());
            i.setPpsn(ppsnTf.getText());
            i.setInjurType(injurTypeTf.getText());
            i.setBloodP(bloodPTf.getText());
            //add object of arraylist
            patients.add(i);
        
        }else if (criticalPatientsRb.isSelected()) {

            CriticalPatients c = new CriticalPatients();
            c.setName(nameTf.getText());
            c.setAge(ageTf.getText());
            c.setGuardNam(guardNamTf.getText());
            c.setPpsn(ppsnTf.getText());
            c.setOperation(operationTf.getText());
            c.setConcent(concentTf.getText());

            patients.add(c);
        }
        clearFields();
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        if (patients.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no patient details in the system");
        } else {
            for (int i = 0; i < patients.size(); i++) {
                JOptionPane.showMessageDialog(null, patients.get(i).getDetails());

            }
        }
        
    }//GEN-LAST:event_displayBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        if (patients.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no patient to search");
        } else {
            String SearchTerm = ppsnTf.getText();

            for (Patients p : patients) {
                if (p.getPpsn().equalsIgnoreCase(SearchTerm)) {
                    JOptionPane.showMessageDialog(null, p.getDetails());
                }

            }

        }
        clearFields();
    }//GEN-LAST:event_searchBtnActionPerformed
    private void clearFields(){
        nameTf.setText(" ");
        ageTf.setText(" ");
        guardNamTf.setText(" ");
        ppsnTf.setText(" ");
        symptomsTf.setText(" ");
        symDurationTf.setText(" ");
        injurTypeTf.setText(" ");
        bloodPTf.setText(" ");
        operationTf.setText(" ");
        concentTf.setText(" "); 
        
    }
    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        if (patients.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no patient to remove");
        } else {
            String SearchTerm = ppsnTf.getText();
            for (int i = 0; i < patients.size(); i++) {
                Patients p = patients.get(i);

                if (p.getPpsn().equalsIgnoreCase(SearchTerm)) {

                    patients.remove(p);
                    
                }

            }
        }
        clearFields();
    }//GEN-LAST:event_removeBtnActionPerformed

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        // TODO add your handling code here:
         MenuGUI myGUI = new MenuGUI();
        myGUI.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_menuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientsGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTf;
    private javax.swing.JLabel bloodPLbl;
    private javax.swing.JTextField bloodPTf;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel concentLbl;
    private javax.swing.JTextField concentTf;
    private javax.swing.JRadioButton criticalPatientsRb;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel guardNamLbl;
    private javax.swing.JTextField guardNamTf;
    private javax.swing.JLabel injurTypeLbl;
    private javax.swing.JTextField injurTypeTf;
    private javax.swing.JRadioButton injuredPatientsRb;
    private javax.swing.JButton menuBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTf;
    private javax.swing.JLabel operationLbl;
    private javax.swing.JTextField operationTf;
    private javax.swing.JRadioButton ordinaryPatientsRb;
    private javax.swing.JLabel ppsnLbl;
    private javax.swing.JTextField ppsnTf;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel symDurationLbl;
    private javax.swing.JTextField symDurationTf;
    private javax.swing.JLabel symptomsLbl;
    private javax.swing.JTextField symptomsTf;
    private javax.swing.JLabel title1Lbl;
    // End of variables declaration//GEN-END:variables
}
